# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/07 22:14:41 by clorin            #+#    #+#              #
#    Updated: 2023/09/07 22:15:25 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


RESULT = Test
SOURCES = people.ml main.ml

OCAMLMAKEFILE = ../../OCamlMakefile
include $(OCAMLMAKEFILE)