# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/25 11:25:31 by clorin            #+#    #+#              #
#    Updated: 2023/07/28 09:35:19 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = Test
SOURCES = gardening.ml
LIBS = $(WITHGRAPHICS)
WITHGRAPHICS =graphics
OCAMLMAKEFILE = ../../OCamlMakefile
include $(OCAMLMAKEFILE)
