# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/30 21:31:47 by clorin            #+#    #+#              #
#    Updated: 2023/08/30 21:33:30 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = Test
SOURCES = cipher.ml uncipher.ml main.ml

OCAMLMAKEFILE = ../../OCamlMakefile
include $(OCAMLMAKEFILE)