# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/04 14:49:41 by clorin            #+#    #+#              #
#    Updated: 2023/09/04 14:55:23 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = Test
SOURCES = Deck.mli Deck.ml main.ml

OCAMLMAKEFILE = ../../OCamlMakefile
include $(OCAMLMAKEFILE)